{{- if not .Values.minio.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-mysqldump-tominio-cron.fullname" . }}-minio
  labels:
    {{- include "kube-mysqldump-tominio-cron.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.minio.existingSecretServerKey }}: {{ .Values.minio.server | quote }}
  {{ .Values.minio.existingSecretAccessKeyKey }}: {{ .Values.minio.accessKey | quote }}
  {{ .Values.minio.existingSecretSecretKeyKey }}: {{ .Values.minio.secretKey | quote }}
  {{ .Values.minio.existingSecretBucketKey }}: {{ .Values.minio.bucket | quote }}
{{- end }}
