{{- if not .Values.mysql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-mysqldump-tominio-cron.fullname" . }}-mysql
  labels:
    {{- include "kube-mysqldump-tominio-cron.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.mysql.existingSecretUsernameKey }}: {{ .Values.mysql.user | quote }}
  {{ .Values.mysql.existingSecretPasswordKey }}: {{ .Values.mysql.password | quote }}
{{- end }}
